CREATE DATABASE IF NOT EXISTS simulador;

USE simulador;

CREATE TABLE IF NOT EXISTS cuentas(
    ID_Cuenta INT AUTO_INCREMENT PRIMARY KEY,
    NombreCliente VARCHAR(255) NOT NULL,
    Saldo DECIMAL(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS transacciones(
    ID_Trans INT AUTO_INCREMENT PRIMARY KEY,
    ID_Cuenta INT NOT NULL,
    Tipo VARCHAR(30) NOT NULL,
    Monto DECIMAL(10,2) NOT NULL,
    Fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_Cuenta) REFERENCES cuentas(ID_Cuenta)
);